minor fix

diff --git a/hooks/pre-commit-clang-format b/hooks/pre-commit-clang-format
--- a/hooks/pre-commit-clang-format
+++ b/hooks/pre-commit-clang-format
@@ -3,19 +3,23 @@
 # clang-formatting
 echo "Executing clang-formatting pre-commit hook..."
 
-FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\\.(cpp|h)$")
+CLANG_FORMAT_FILE="graph_core/graph_core/.clang-format"
 
-if [ -n "$FILES" ]; then
-  echo "Formatting files:"
-  echo "$FILES"
-  echo
-
-  CLANG_FORMAT_FILE="graph_core/graph_core/.clang-format"
-
-  echo "Using clang-format configuration from: $(realpath "$CLANG_FORMAT_FILE")"
-
-  for FILE in $FILES; do
-    clang-format -i --style=file --assume-filename="$CLANG_FORMAT_FILE" "$FILE"
-    git add "$FILE"
-  done
+if ! command -v clang-format &> /dev/null; then
+  echo "Error: clang-format is not installed. Please install it and try again."
+  exit 1
 fi
+
+if [ ! -f "$CLANG_FORMAT_FILE" ]; then
+  echo "Error: .clang-format file not found at $CLANG_FORMAT_FILE"
+  exit 1
+fi
+
+echo "Using clang-format configuration from: $(realpath "$CLANG_FORMAT_FILE")"
+
+for FILE in "$@"; do
+  echo "Formatting $FILE"
+  clang-format -i --style=file --assume-filename="$CLANG_FORMAT_FILE" "$FILE"
+  git add "$FILE"
+done
+
